services:
  newsletter-generator-crewai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "src/gui/app.py"]
